-- 예약 테이블
CREATE TABLE RESERVATION (
    RSV_NO NUMBER PRIMARY KEY,
    RSV_MEMBER_NO NUMBER NOT NULL,
    RSV_SEAT_CODE CHAR(2) NOT NULL,
    RSV_TIME_CODE CHAR(2) NOT NULL,
    RSV_TOTAL_PRICE NUMBER NOT NULL,
    REGIST_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE,
    DEL_DATE DATE,
    CONSTRAINT FK_RESERVATION_MEMBER_NO FOREIGN KEY (RSV_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_RESERVATION_SEAT FOREIGN KEY (RSV_SEAT_CODE) REFERENCES SEAT(SEAT_CODE),
    CONSTRAINT FK_RESERVATION_TIME_CODE FOREIGN KEY (RSV_TIME_CODE) REFERENCES TIME(TIME_CODE)
);

-- 예약 넘버링 시퀸스
CREATE SEQUENCE SEQ_RSV_NO;

-- TIME 테이블
CREATE TABLE TIME (
	TIME_CODE CHAR(2) PRIMARY KEY,
	START_TIME DATE NOT NULL,
	END_TIME DATE NOT NULL
)

-- SEAT 테이블
CREATE TABLE SEAT (
	SEAT_CODE CHAR(2) PRIMARY KEY,
	SEAT_STATUS NUMBER(1,0) DEFAULT 0 CHECK (SEAT_STATUS IN (0, 1)) NOT NULL
)

-- SERVICE 테이블
CREATE TABLE SERVICE (
	SERVICE_CODE CHAR(2) PRIMARY KEY,
	CONTENT VARCHAR2(50) NOT NULL
)

-- time_seat_map
CREATE TABLE TIME_SEAT_MAP (
	TIME_CODE CHAR(2),
	SEAT_CODE CHAR(2),
    CONSTRAINT PK_TIME_SEAT_MAP PRIMARY KEY (TIME_CODE, SEAT_CODE),
	CONSTRAINT FK_TIME_SEAT_MAP_TIME_CODE FOREIGN KEY (TIME_CODE) REFERENCES TIME(TIME_CODE),
	CONSTRAINT FK_TIME_SEAT_MAP_SEAT_CODE FOREIGN KEY (SEAT_CODE) REFERENCES SEAT(SEAT_CODE)
)

CREATE TABLE SEAT_SERVICE_MAP (
    SEAT_CODE CHAR(2),
    SERVICE_CODE CHAR(2),
    CONSTRAINT PK_SEAT_SERVICE_MAP PRIMARY KEY (SEAT_CODE, SERVICE_CODE),
    CONSTRAINT FK_SEAT_SERVICE_MAP_SEAT_CODE FOREIGN KEY (SEAT_CODE) REFERENCES SEAT(SEAT_CODE),
    CONSTRAINT FK_SEAT_SERVICE_MAP_SERVICE FOREIGN KEY (SERVICE_CODE) REFERENCES SERVICE(SERVICE_CODE)
);

CREATE TABLE RESERVATION_PRODUCT_MAP (
	RSV_NO NUMBER,
	PRODUCT_NO NUMBER,
	QUANTITY NUMBER,
	CONSTRAINT PK_REV_PRD_MAP PRIMARY KEY (RSV_NO, PRODUCT_NO),
    CONSTRAINT FK__REV_PRD_MAP_RSV_NO FOREIGN KEY (RSV_NO) REFERENCES RESERVATION(RSV_NO),
    CONSTRAINT FK__REV_PRD_MAP_PRODUCT_NO FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)
);

-- 예약 시간 불러오기
SELECT
      TO_CHAR(START_TIME, 'HH24:MI') AS START_TIME
    , TO_CHAR(END_TIME, 'HH24:MI') AS END_TIME
FROM TIME
WHERE TIME_CODE = ?

-- 예약된 테이블 찾기 Seat 기준
SELECT A.SEAT_CODE
FROM SEAT A
LEFT JOIN TIME_SEAT_MAP B ON A.SEAT_CODE = B.SEAT_CODE
LEFT JOIN RESERVATION C ON B.TIME_CODE = C.RSV_TIME_CODE
AND B.SEAT_CODE = C.RSV_SEAT_CODE
WHERE C.RSV_TIME_CODE IS NULL
AND B.TIME_CODE = ?

-- 상품 목록 불러오기
SELECT
      A.PRODUCT_NO
    , A.NAME
    , A.PRICE
    , B.NAME AS C_NAME
FROM PRODUCT A
LEFT JOIN CATEGORY B ON B.CATEGORYCODE = A.CATEGORYCODE
ORDER BY C_NAME, A.PRICE

-- 예약 INSERT
INSERT INTO RESERVATION (
      RSV_NO
    , RSV_MEMBER_NO
    , RSV_SEAT_CODE
    , RSV_TIME_CODE
    , RSV_TOTAL_PRICE
    , REGIST_DATE)
VALUES (SEQ_RSV_NO.NEXTVAL, 123, 'A1', 'T1', 15000, SYSDATE);